application: cool-maze
version: 0-0-1
runtime: go
api_version: go1

handlers:
- url: /dispatch
  script: _go_app
- url: /ack
  script: _go_app
- url: /wakeup
  script: _go_app
- url: /new-gcs-urls
  script: _go_app