application: cool-maze
module: default
version: dev
runtime: go
api_version: go1

handlers:
- url: /online
  static_files: online.json
  upload: online\.json
  expiration: "0s"
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: _go_app
  secure: always